name: Build Tokens

on:
  push:
    paths:
      - 'tokens/**'
      - 'config.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Style Dictionary
        run: npm install style-dictionary

      - name: Build tokens
        run: npx style-dictionary build --config config.json

      - name: Commit generated files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add build/
          git commit -m "Update token builds"
          git push
